export const FORMAT_DATE = {
  FORMAT_DATE_FOR_API_REQUEST: "YYYY-MM-DDTHH:mm:ssZ",

  FORMAT_DATE_FOR_DATE_AND_A_HALF_DAY_TIME_AND_INTERVALS: "D-M-YYYY h:m A",

  FORMAT_DATE_FOR_DATE_AND_FULL_DAY_TIME: "DD-MM-YYYY HH:mm:ss",

  FORMAT_DATE_FOR_DATE_ONLY: "DD-MM-YYYY",

  FORMAT_DATE_FOR_FULL_DAY_TIME_ONLY: "HH:mm:ss",
};
