export const FORMAT_DATE = {
  FORMAT_DATE_FOR_API_REQUEST: "YYYY-MM-DDTHH:mm:ssZ",

  FORMAT_DATE_FOR_DATE_TIME_A: "D-M-YYYY h:m A",

  FORMAT_DATE_FOR_DATE_TIME: "DD-MM-YYYY HH:mm:ss",

  FORMAT_DATE_FOR_DATE: "DD-MM-YYYY",

  FORMAT_DATE_FOR_TIME: "HH:mm:ss",
};
