export const FORMAT_DATE = {
  FORMAT_DATE_FOR_API_REQUEST: "YYYY-MM-DDTHH:mm:ssZ",

  FORMAT_DATE_FOR_DATE_AND_12_HOURS_AND_INTERVALS: "D-M-YYYY h:m A",

  FORMAT_DATE_FOR_DATE_AND_24_HOURS: "DD-MM-YYYY HH:mm:ss",

  FORMAT_DATE_FOR_DATE_ONLY: "DD-MM-YYYY",

  FORMAT_DATE_FOR_24_HOURS_ONLY: "HH:mm:ss",
};
